services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  estoque-service:
    build:
      context: ./estoque-service
    container_name: estoque-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=estoque_db;Username=postgres;Password=postgres
    ports:
      - "5001:8080"

  faturamento-service:
    build:
      context: ./faturamento-service
    container_name: faturamento-service
    depends_on:
      postgres:
        condition: service_healthy
      estoque-service:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=faturamento_db;Username=postgres;Password=postgres
      Services__EstoqueBaseUrl: http://estoque-service:8080
    ports:
      - "5002:8080"

  frontend-angular:
    build:
      context: ./frontend-angular
    container_name: frontend-angular
    depends_on:
      estoque-service:
        condition: service_started
      faturamento-service:
        condition: service_started
    ports:
      - "4200:80"

volumes:
  postgres_data:
